[package]
name = "ippdme-py"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Python bindings for ippdme, distributed via Maturin"

[lib]
name = "_ippdme"
crate-type = ["cdylib", "rlib"]

[dependencies]
ippdme-core = { workspace = true }
ippdme-net = { workspace = true, features = ["tls"] }
pyo3 = { version = "0.22", features = ["extension-module"] }
tokio = { workspace = true }
